zip:
	$(RM) -v q?.zip
	zip q1.zip Needleman-Wunsch/q1/src/main.c Needleman-Wunsch/src/nw.? Needleman-Wunsch/q1/*.md Needleman-Wunsch/q1/Makefile Needleman-Wunsch/q1/obj Needleman-Wunsch/q1/bin
	zip q2.zip Needleman-Wunsch/q2/src/main.c Needleman-Wunsch/src/nw.? Needleman-Wunsch/q2/*.md Needleman-Wunsch/q2/Makefile Needleman-Wunsch/q2/obj Needleman-Wunsch/q2/bin
